### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range 0..3: 4

### ISSUE THREAD

**Issue by carrasc0** [marcglasberg/indexed_list_view#34] opened 2021-11-11 16:00 UTC
Throwing this exception with the provided example. I guess because itemCount is not provided

**Comment by yasirrose** [comment] 2021-11-18 21:12
I am trying to paginate the list using indexed_list_view but getting the "RangeError (index): Invalid value: Not in
inclusive range 0..9" error on loading data.

**Comment by marcglasberg** [comment] 2021-12-23 05:37
I'll try to have a look at it during the weekend. This was working ok, so probably some recent Flutter version changed something.

**Comment by marcglasberg** [comment] 2021-12-23 17:53
@carrasc0 

Please, which provided example? I tried these:

  main.dart
  main_page_storage_key.dart
  main_with_finite_items.dart
  main_with_item_count.dart

I can't see any exceptions with those? Could you please help me reproduce the problem?

**Comment by marcglasberg** [comment] 2021-12-23 18:03
@carrasc0 
@yasirrose 

The itemBuilder has this signature:

```
typedef IndexedWidgetBuilderOrNull = Widget? Function(BuildContext context, int index);
```

The list is infinite. This means you can just pass the index to a list. For example, if your list has 100 items, it will fail when index is `> 100` or `< 0`. What you need to do is check the index. For example:

```
List<String> myList = [...];

Widget? Function(BuildContext context, int index) {
if (index<0 || index >= myList.length) return null;
else return Text(myList[index]);
}
```

**Comment by marcglasberg** [comment] 2021-12-23 18:04
@carrasc0

Please, which provided example? I tried these:

```
main.dart
main_page_storage_key.dart
main_with_finite_items.dart
main_with_item_count.dart
```

I can't see it throw any exceptions with those? Could you please help me reproduce the problem?

**Comment by marcglasberg** [comment] 2021-12-25 20:50
Closing this. Will reopen if more info becomes available.

**Closed as completed by marcglasberg** 2021-12-25 20:50 UTC

**Comment by danger-ahead** [comment] 2022-01-02 12:11
Facing the same error. The fix didn't work

**Comment by marcglasberg** [comment] 2022-01-03 17:26
@danger-ahead Could you please provide me with the code for your `itemBuilder`?

**Comment by danger-ahead** [comment] 2022-01-03 17:34
Umm sorry. I am not using this library any more. But the problem was exactly what has been mentioned by the issue opener. The children widgets were okay. But I could scroll both up and down beyond the actual children widgets (actually resulted in red the usual red areas that arise when there's an error).

**Comment by marcglasberg** [comment] 2022-01-03 20:13
To anyone reaching this issue:

* This library is for INFINITE lists ONLY. For that use case, it works just fine and has no bugs.
* It will ALWAYS scroll down to negative and up to positive infinity. For example: A calendar. Your `itemBuilder` should be able to deal with any `index`.
* Your `itemBuilder` may return null. In that case, the `emptyItemBuilder` callback will return an "empty" item to be displayed instead. As default, this will return empty containers.
* If you need a FINITE list, you can NOT use this widget. I suggest an alternative for that case is using https://pub.dev/packages/scrollable_positioned_list which unfortunately has many bugs that never get fixed. But it's still the best FINITE LIST alternative at the moment.

Hope this helps!

**Comment by kevin4dhd** [comment] 2024-08-29 13:18
any update for finite list?

**Comment by marcglasberg** [comment] 2024-08-29 20:03
@kevin4dhd No, this widget is for infinite lists only, and that won't change. For finite lists you can maybe try https://pub.dev/packages/scrollable_positioned_list or search some other widget.
